#!/bin/bash
export ORACLE_SID=ora12c
#export FROMUSER=FED_SYSTEM_V4
#export FROMUSER=`basename $0`
#echo $USERNAME
#export USERNAME=$FROMUSER
echo "PLEASE INPUT OFSAA DUMP FILE NAME: "
read FROMUSER
#echo "PLEASE INPUT TOUSER NAME: "
#read USERNAME
#echo "IMPORTING $FROMUSER BACKUP FILE INTO $USERNAME!"
export DUMPFILE=$FROMUSER.dmp
export DIRECTORY=/home/oracle/backup
export LOGFILE=OFSAA.log
echo $LOGFILE


impdp dumpfile=$DUMPFILE userid=system/0racle1 directory=EXPORT logfile=$LOGFILE

